from typing import Any, Dict, Optional

WORDING : Dict[str, Any] =\
{
	'conda_not_activated': 'Conda is not activated',
	'python_not_supported': 'Python version is not supported, upgrade to {version} or higher',
	'curl_not_installed': 'cURL is not installed',
	'ffmpeg_not_installed': 'FFMpeg is not installed',
	'creating_temp': 'Creating temporary resources',
	'extracting_frames': 'Extracting frames with a resolution of {resolution} and {fps} frames per second',
	'extracting_frames_succeed': 'Extracting frames succeed',
	'extracting_frames_failed': 'Extracting frames failed',
	'analysing': 'Analysing',
	'extracting': 'Extracting',
	'streaming': 'Streaming',
	'processing': 'Processing',
	'merging': 'Merging',
	'downloading': 'Downloading',
	'temp_frames_not_found': 'Temporary frames not found',
	'copying_image': 'Copying image with a resolution of {resolution}',
	'copying_image_succeed': 'Copying image succeed',
	'copying_image_failed': 'Copying image failed',
	'finalizing_image': 'Finalizing image with a resolution of {resolution}',
	'finalizing_image_succeed': 'Finalizing image succeed',
	'finalizing_image_skipped': 'Finalizing image skipped',
	'merging_video': 'Merging video with a resolution of {resolution} and {fps} frames per second',
	'merging_video_succeed': 'Merging video succeed',
	'merging_video_failed': 'Merging video failed',
	'skipping_audio': 'Skipping audio',
	'replacing_audio_succeed': 'Replacing audio succeed',
	'replacing_audio_skipped': 'Replacing audio skipped',
	'restoring_audio_succeed': 'Restoring audio succeed',
	'restoring_audio_skipped': 'Restoring audio skipped',
	'clearing_temp': 'Clearing temporary resources',
	'processing_stopped': 'Processing stopped',
	'processing_image_succeed': 'Processing to image succeed in {seconds} seconds',
	'processing_image_failed': 'Processing to image failed',
	'processing_video_succeed': 'Processing to video succeed in {seconds} seconds',
	'processing_video_failed': 'Processing to video failed',
	'choose_image_source': 'Choose a image for the source',
	'choose_audio_source': 'Choose a audio for the source',
	'choose_video_target': 'Choose a video for the target',
	'choose_image_or_video_target': 'Choose a image or video for the target',
	'specify_image_or_video_output': 'Specify the output image or video within a directory',
	'match_target_and_output_extension': 'Match the target and output extension',
	'no_source_face_detected': 'No source face detected',
	'processor_not_loaded': 'Processor {processor} could not be loaded',
	'processor_not_implemented': 'Processor {processor} not implemented correctly',
	'ui_layout_not_loaded': 'UI layout {ui_layout} could not be loaded',
	'ui_layout_not_implemented': 'UI layout {ui_layout} not implemented correctly',
	'stream_not_loaded': 'Stream {stream_mode} could not be loaded',
	'stream_not_supported': 'Stream not supported',
	'job_created': 'Job {job_id} created',
	'job_not_created': 'Job {job_id} not created',
	'job_submitted': 'Job {job_id} submitted',
	'job_not_submitted': 'Job {job_id} not submitted',
	'job_all_submitted': 'Jobs submitted',
	'job_all_not_submitted': 'Jobs not submitted',
	'job_deleted': 'Job {job_id} deleted',
	'job_not_deleted': 'Job {job_id} not deleted',
	'job_all_deleted': 'Jobs deleted',
	'job_all_not_deleted': 'Jobs not deleted',
	'job_step_added': 'Step added to job {job_id}',
	'job_step_not_added': 'Step not added to job {job_id}',
	'job_remix_step_added': 'Step {step_index} remixed from job {job_id}',
	'job_remix_step_not_added': 'Step {step_index} not remixed from job {job_id}',
	'job_step_inserted': 'Step {step_index} inserted to job {job_id}',
	'job_step_not_inserted': 'Step {step_index} not inserted to job {job_id}',
	'job_step_removed': 'Step {step_index} removed from job {job_id}',
	'job_step_not_removed': 'Step {step_index} not removed from job {job_id}',
	'running_job': 'Running queued job {job_id}',
	'running_jobs': 'Running all queued jobs',
	'retrying_job': 'Retrying failed job {job_id}',
	'retrying_jobs': 'Retrying all failed jobs',
	'processing_job_succeed': 'Processing of job {job_id} succeed',
	'processing_jobs_succeed': 'Processing of all job succeed',
	'processing_job_failed': 'Processing of job {job_id} failed',
	'processing_jobs_failed': 'Processing of all jobs failed',
	'processing_step': 'Processing step {step_current} of {step_total}',
	'validating_hash_succeed': 'Validating hash for {hash_file_name} succeed',
	'validating_hash_failed': 'Validating hash for {hash_file_name} failed',
	'validating_source_succeed': 'Validating source for {source_file_name} succeed',
	'validating_source_failed': 'Validating source for {source_file_name} failed',
	'deleting_corrupt_source': 'Deleting corrupt source for {source_file_name}',
	'time_ago_now': 'just now',
	'time_ago_minutes': '{minutes} minutes ago',
	'time_ago_hours': '{hours} hours and {minutes} minutes ago',
	'time_ago_days': '{days} days, {hours} hours and {minutes} minutes ago',
	'point': '.',
	'comma': ',',
	'colon': ':',
	'question_mark': '?',
	'exclamation_mark': '!',
	'help':
	{
		# installer
		'install_dependency': 'choose the variant of {dependency} to install',
		'skip_conda': 'skip the conda environment check',
		# paths
		'config_path': 'choose the config file to override defaults',
		'temp_path': 'specify the directory for the temporary resources',
		'jobs_path': 'specify the directory to store jobs',
		'source_paths': 'choose the image or audio paths',
		'target_path': 'choose the image or video path',
		'output_path': 'specify the image or video within a directory',
		# patterns
		'source_pattern': 'choose the image or audio pattern',
		'target_pattern': 'choose the image or video pattern',
		'output_pattern': 'specify the image or video pattern',
		# face detector
		'face_detector_model': 'choose the model responsible for detecting the faces',
		'face_detector_size': 'specify the frame size provided to the face detector',
		'face_detector_angles': 'specify the angles to rotate the frame before detecting faces',
		'face_detector_score': 'filter the detected faces base on the confidence score',
		# face landmarker
		'face_landmarker_model': 'choose the model responsible for detecting the face landmarks',
		'face_landmarker_score': 'filter the detected face landmarks base on the confidence score',
		# face selector
		'face_selector_mode': 'use reference based tracking or simple matching',
		'face_selector_order': 'specify the order of the detected faces',
		'face_selector_age_start': 'filter the detected faces based the starting age',
		'face_selector_age_end': 'filter the detected faces based the ending age',
		'face_selector_gender': 'filter the detected faces based on their gender',
		'face_selector_race': 'filter the detected faces based on their race',
		'reference_face_position': 'specify the position used to create the reference face',
		'reference_face_distance': 'specify the similarity between the reference face and target face',
		'reference_frame_number': 'specify the frame used to create the reference face',
		# face masker
		'face_occluder_model': 'choose the model responsible for the occlusion mask',
		'face_parser_model': 'choose the model responsible for the region mask',
		'face_mask_types': 'mix and match different face mask types (choices: {choices})',
		'face_mask_areas': 'choose the items used for the area mask (choices: {choices})',
		'face_mask_regions': 'choose the items used for the region mask (choices: {choices})',
		'face_mask_blur': 'specify the degree of blur applied to the box mask',
		'face_mask_padding': 'apply top, right, bottom and left padding to the box mask',
		# frame extraction
		'trim_frame_start': 'specify the starting frame of the target video',
		'trim_frame_end': 'specify the ending frame of the target video',
		'temp_frame_format': 'specify the temporary resources format',
		'keep_temp': 'keep the temporary resources after processing',
		# output creation
		'output_image_quality': 'specify the image quality which translates to the image compression',
		'output_image_resolution': 'specify the image resolution based on the target image',
		'output_audio_encoder': 'specify the encoder used for the audio',
		'output_audio_quality': 'specify the audio quality which translates to the audio compression',
		'output_audio_volume': 'specify the audio volume based on the target video',
		'output_video_encoder': 'specify the encoder used for the video',
		'output_video_preset': 'balance fast video processing and video file size',
		'output_video_quality': 'specify the video quality which translates to the video compression',
		'output_video_resolution': 'specify the video resolution based on the target video',
		'output_video_fps': 'specify the video fps based on the target video',
		# processors
		'processors': 'load a single or multiple processors (choices: {choices}, ...)',
		'age_modifier_model': 'choose the model responsible for aging the face',
		'age_modifier_direction': 'specify the direction in which the age should be modified',
		'deep_swapper_model': 'choose the model responsible for swapping the face',
		'deep_swapper_morph': 'morph between source face and target faces',
		'expression_restorer_model': 'choose the model responsible for restoring the expression',
		'expression_restorer_factor': 'restore factor of expression from the target face',
		'face_debugger_items': 'load a single or multiple processors (choices: {choices})',
		'face_editor_model': 'choose the model responsible for editing the face',
		'face_editor_eyebrow_direction': 'specify the eyebrow direction',
		'face_editor_eye_gaze_horizontal': 'specify the horizontal eye gaze',
		'face_editor_eye_gaze_vertical': 'specify the vertical eye gaze',
		'face_editor_eye_open_ratio': 'specify the ratio of eye opening',
		'face_editor_lip_open_ratio': 'specify the ratio of lip opening',
		'face_editor_mouth_grim': 'specify the mouth grim',
		'face_editor_mouth_pout': 'specify the mouth pout',
		'face_editor_mouth_purse': 'specify the mouth purse',
		'face_editor_mouth_smile': 'specify the mouth smile',
		'face_editor_mouth_position_horizontal': 'specify the horizontal mouth position',
		'face_editor_mouth_position_vertical': 'specify the vertical mouth position',
		'face_editor_head_pitch': 'specify the head pitch',
		'face_editor_head_yaw': 'specify the head yaw',
		'face_editor_head_roll': 'specify the head roll',
		'face_enhancer_model': 'choose the model responsible for enhancing the face',
		'face_enhancer_blend': 'blend the enhanced into the previous face',
		'face_enhancer_weight': 'specify the degree of weight applied to the face',
		'face_swapper_model': 'choose the model responsible for swapping the face',
		'face_swapper_pixel_boost': 'choose the pixel boost resolution for the face swapper',
		'frame_colorizer_model': 'choose the model responsible for colorizing the frame',
		'frame_colorizer_size': 'specify the frame size provided to the frame colorizer',
		'frame_colorizer_blend': 'blend the colorized into the previous frame',
		'frame_enhancer_model': 'choose the model responsible for enhancing the frame',
		'frame_enhancer_blend': 'blend the enhanced into the previous frame',
		'lip_syncer_model': 'choose the model responsible for syncing the lips',
		'lip_syncer_weight': 'specify the degree of weight applied to the lips',
		# uis
		'open_browser': 'open the browser once the program is ready',
		'ui_layouts': 'launch a single or multiple UI layouts (choices: {choices}, ...)',
		'ui_workflow': 'choose the ui workflow',
		# download
		'download_providers': 'download using different providers (choices: {choices}, ...)',
		'download_scope': 'specify the download scope',
		# benchmark
		'benchmark_resolutions': 'choose the resolutions for the benchmarks (choices: {choices}, ...)',
		'benchmark_cycle_count': 'specify the amount of cycles per benchmark',
		# execution
		'execution_device_id': 'specify the device used for processing',
		'execution_providers': 'inference using different providers (choices: {choices}, ...)',
		'execution_thread_count': 'specify the amount of parallel threads while processing',
		'execution_queue_count': 'specify the amount of frames each thread is processing',
		# memory
		'video_memory_strategy': 'balance fast processing and low VRAM usage',
		'system_memory_limit': 'limit the available RAM that can be used while processing',
		# misc
		'log_level': 'adjust the message severity displayed in the terminal',
		'halt_on_error': 'halt the program once an error occurred',
		# run
		'run': 'run the program',
		'headless_run': 'run the program in headless mode',
		'batch_run': 'run the program in batch mode',
		'force_download': 'force automate downloads and exit',
		'benchmark': 'benchmark the program',
		# jobs
		'job_id': 'specify the job id',
		'job_status': 'specify the job status',
		'step_index': 'specify the step index',
		# job manager
		'job_list': 'list jobs by status',
		'job_create': 'create a drafted job',
		'job_submit': 'submit a drafted job to become a queued job',
		'job_submit_all': 'submit all drafted jobs to become a queued jobs',
		'job_delete': 'delete a drafted, queued, failed or completed job',
		'job_delete_all': 'delete all drafted, queued, failed and completed jobs',
		'job_add_step': 'add a step to a drafted job',
		'job_remix_step': 'remix a previous step from a drafted job',
		'job_insert_step': 'insert a step to a drafted job',
		'job_remove_step': 'remove a step from a drafted job',
		# job runner
		'job_run': 'run a queued job',
		'job_run_all': 'run all queued jobs',
		'job_retry': 'retry a failed job',
		'job_retry_all': 'retry all failed jobs'
	},
	'about':
	{
		'become_a_member': 'become a member',
		'join_our_community': 'join our community',
		'read_the_documentation': 'read the documentation'
	},
	'uis':
	{
		'age_modifier_direction_slider': 'AGE MODIFIER DIRECTION 年齡修改器方向',
		'age_modifier_model_dropdown': 'AGE MODIFIER MODEL 年齡修改器模型',
		'apply_button': 'APPLY 應用',
		'benchmark_cycle_count_slider': 'BENCHMARK CYCLE COUNT 基準測試周期',
		'benchmark_resolutions_checkbox_group': 'BENCHMARK RESOLUTIONS 基準測試運行',
		'clear_button': 'CLEAR 清除',
		'common_options_checkbox_group': 'OPTIONS 通用選項',
		'download_providers_checkbox_group': 'DOWNLOAD PROVIDERS 下載來源',
		'deep_swapper_model_dropdown': 'DEEP SWAPPER MODEL 深度交換器模型',
		'deep_swapper_morph_slider': 'DEEP SWAPPER MORPH 深度交換變形程度',
		'execution_providers_checkbox_group': 'EXECUTION PROVIDERS 執行提供者',
		'execution_queue_count_slider': 'EXECUTION QUEUE COUNT 執行佇列數',
		'execution_thread_count_slider': 'EXECUTION THREAD COUNT 執行執行緒數',
		'expression_restorer_factor_slider': 'EXPRESSION RESTORER FACTOR 表情恢復因子',
		'expression_restorer_model_dropdown': 'EXPRESSION RESTORER MODEL 表情恢復模型',
		'face_debugger_items_checkbox_group': 'FACE DEBUGGER ITEMS 臉部除錯項目',
		'face_detector_angles_checkbox_group': 'FACE DETECTOR ANGLES 臉部偵測角度',
		'face_detector_model_dropdown': 'FACE DETECTOR MODEL 臉部偵測模型',
		'face_detector_score_slider': 'FACE DETECTOR SCORE 臉部偵測分數',
		'face_detector_size_dropdown': 'FACE DETECTOR SIZE 臉部偵測尺寸',
		'face_editor_eyebrow_direction_slider': 'FACE EDITOR EYEBROW DIRECTION 臉部編輯器眉毛方向',
		'face_editor_eye_gaze_horizontal_slider': 'FACE EDITOR EYE GAZE HORIZONTAL 臉部編輯器眼睛水平視線',
		'face_editor_eye_gaze_vertical_slider': 'FACE EDITOR EYE GAZE VERTICAL 臉部編輯器眼睛垂直視線',
		'face_editor_eye_open_ratio_slider': 'FACE EDITOR EYE OPEN RATIO 臉部編輯器眼睛張開比例',
		'face_editor_head_pitch_slider': 'FACE EDITOR HEAD PITCH 臉部編輯器頭部俯仰',
		'face_editor_head_roll_slider': 'FACE EDITOR HEAD ROLL 臉部編輯器頭部翻轉',
		'face_editor_head_yaw_slider': 'FACE EDITOR HEAD YAW 臉部編輯器頭部偏擺',
		'face_editor_lip_open_ratio_slider': 'FACE EDITOR LIP OPEN RATIO 臉部編輯器嘴唇張開比例',
		'face_editor_model_dropdown': 'FACE EDITOR MODEL 臉部編輯器模型',
		'face_editor_mouth_grim_slider': 'FACE EDITOR MOUTH GRIM 臉部編輯器嘴部緊繃',
		'face_editor_mouth_position_horizontal_slider': 'FACE EDITOR MOUTH POSITION HORIZONTAL 臉部編輯器嘴巴水平位置',
		'face_editor_mouth_position_vertical_slider': 'FACE EDITOR MOUTH POSITION VERTICAL 臉部編輯器嘴巴垂直位置',
		'face_editor_mouth_pout_slider': 'FACE EDITOR MOUTH POUT 臉部編輯器噘嘴程度',
		'face_editor_mouth_purse_slider': 'FACE EDITOR MOUTH PURSE 臉部編輯器嘴巴收縮程度',
		'face_editor_mouth_smile_slider': 'FACE EDITOR MOUTH SMILE 臉部編輯器微笑程度',
		'face_enhancer_blend_slider': 'FACE ENHANCER BLEND 臉部強化混合程度',
		'face_enhancer_model_dropdown': 'FACE ENHANCER MODEL 臉部強化模型',
		'face_enhancer_weight_slider': 'FACE ENHANCER WEIGHT 臉部強化權重',
		'face_landmarker_model_dropdown': 'FACE LANDMARKER MODEL 臉部特徵點模型',
		'face_landmarker_score_slider': 'FACE LANDMARKER SCORE 臉部特徵點分數',
		'face_mask_blur_slider': 'FACE MASK BLUR 臉部遮罩模糊度',
		'face_mask_padding_bottom_slider': 'FACE MASK PADDING BOTTOM 臉部遮罩下邊距',
		'face_mask_padding_left_slider': 'FACE MASK PADDING LEFT 臉部遮罩左邊距',
		'face_mask_padding_right_slider': 'FACE MASK PADDING RIGHT 臉部遮罩右邊距',
		'face_mask_padding_top_slider': 'FACE MASK PADDING TOP 臉部遮罩上邊距',
		'face_mask_areas_checkbox_group': 'FACE MASK AREAS 臉部遮罩區域',
		'face_mask_regions_checkbox_group': 'FACE MASK REGIONS 臉部遮罩範圍',
		'face_mask_types_checkbox_group': 'FACE MASK TYPES 臉部遮罩類型',
		'face_selector_age_range_slider': 'FACE SELECTOR AGE 臉部選擇器年齡範圍',
		'face_selector_gender_dropdown': 'FACE SELECTOR GENDER 臉部選擇器性別',
		'face_selector_mode_dropdown': 'FACE SELECTOR MODE 臉部選擇器模式',
		'face_selector_order_dropdown': 'FACE SELECTOR ORDER 臉部選擇器順序',
		'face_selector_race_dropdown': 'FACE SELECTOR RACE 臉部選擇器種族',
		'face_swapper_model_dropdown': 'FACE SWAPPER MODEL 臉部交換器模型',
		'face_swapper_pixel_boost_dropdown': 'FACE SWAPPER PIXEL BOOST 臉部交換畫質加強',
		'face_occluder_model_dropdown': 'FACE OCCLUDER MODEL 臉部遮擋模型',
		'face_parser_model_dropdown': 'FACE PARSER MODEL 臉部分析模型',
		'frame_colorizer_blend_slider': 'FRAME COLORIZER BLEND 影格上色混合程度',
		'frame_colorizer_model_dropdown': 'FRAME COLORIZER MODEL 影格上色模型',
		'frame_colorizer_size_dropdown': 'FRAME COLORIZER SIZE 影格上色尺寸',
		'frame_enhancer_blend_slider': 'FRAME ENHANCER BLEND 影格強化混合程度',
		'frame_enhancer_model_dropdown': 'FRAME ENHANCER MODEL 影格強化模型',
		'job_list_status_checkbox_group': 'JOB STATUS 任務狀態',
		'job_manager_job_action_dropdown': 'JOB ACTION 任務操作',
		'job_manager_job_id_dropdown': 'JOB ID 任務 ID',
		'job_manager_step_index_dropdown': 'STEP INDEX 步驟索引',
		'job_runner_job_action_dropdown': 'JOB ACTION 任務操作',
		'job_runner_job_id_dropdown': 'JOB ID 任務 ID',
		'lip_syncer_model_dropdown': 'LIP SYNCER MODEL 唇音同步模型',
		'lip_syncer_weight_slider': 'LIP SYNCER WEIGHT 唇音同步權重',
		'log_level_dropdown': 'LOG LEVEL 日誌等級',
		'output_audio_encoder_dropdown': 'OUTPUT AUDIO ENCODER 音訊輸出編碼器',
		'output_audio_quality_slider': 'OUTPUT AUDIO QUALITY 音訊輸出品質',
		'output_audio_volume_slider': 'OUTPUT AUDIO VOLUME 音訊輸出音量',
		'output_image_or_video': 'OUTPUT 輸出',
		'output_image_quality_slider': 'OUTPUT IMAGE QUALITY 圖片輸出品質',
		'output_image_resolution_dropdown': 'OUTPUT IMAGE RESOLUTION 圖片輸出解析度',
		'output_path_textbox': 'OUTPUT PATH 輸出路徑',
		'output_video_encoder_dropdown': 'OUTPUT VIDEO ENCODER 影片輸出編碼器',
		'output_video_fps_slider': 'OUTPUT VIDEO FPS 影片輸出幀率',
		'output_video_preset_dropdown': 'OUTPUT VIDEO PRESET 影片輸出預設值',
		'output_video_quality_slider': 'OUTPUT VIDEO QUALITY 影片輸出品質',
		'output_video_resolution_dropdown': 'OUTPUT VIDEO RESOLUTION 影片輸出解析度',
		'preview_frame_slider': 'PREVIEW FRAME 預覽幀',
		'preview_image': 'PREVIEW 預覽',
		'processors_checkbox_group': 'PROCESSORS 處理器',
		'reference_face_distance_slider': 'REFERENCE FACE DISTANCE 參考臉部距離',
		'reference_face_gallery': 'REFERENCE FACE 參考臉部',
		'refresh_button': 'REFRESH 重新整理',
		'source_file': 'SOURCE 原始檔',
		'start_button': 'START 開始',
		'stop_button': 'STOP 停止',
		'system_memory_limit_slider': 'SYSTEM MEMORY LIMIT 系統記憶體限制',
		'target_file': 'TARGET 目標檔案',
		'temp_frame_format_dropdown': 'TEMP FRAME FORMAT 暫存影格格式',
		'terminal_textbox': 'TERMINAL 終端機',
		'trim_frame_slider': 'TRIM FRAME 裁剪影格',
		'ui_workflow': 'UI WORKFLOW 使用介面工作流程',
		'video_memory_strategy_dropdown': 'VIDEO MEMORY STRATEGY 影像記憶體策略',
		'webcam_fps_slider': 'WEBCAM FPS 網路攝影機幀率',
		'webcam_image': 'WEBCAM 網路攝影機',
		'webcam_device_id_dropdown': 'WEBCAM DEVICE ID 攝影機裝置編號',
		'webcam_mode_radio': 'WEBCAM MODE 攝影機模式',
		'webcam_resolution_dropdown': 'WEBCAM RESOLUTION 攝影機解析度'
	}
}


def get(notation : str) -> Optional[str]:
	current = WORDING

	for fragment in notation.split('.'):
		if fragment in current:
			current = current.get(fragment)
			if isinstance(current, str):
				return current

	return None
